# language: node_js
# node_js:
#   - "7"
# cache:
#   yarn: true
#   directories:
#     - node_modules
sudo: required

services:
  - docker

before_install:
- docker pull node:alpine
- docker pull nginx:1.13.12-alpine

script:
- docker build -t bilalfazlani/feature-toggles-ui:latest .
- docker tag bilalfazlani/feature-toggles-ui:latest bilalfazlani/feature-toggles-ui:0.0.$TRAVIS_BUILD_NUMBER
- docker images | grep bilalfazlani/feature-toggles-ui

deploy:
  # deploy to dockerhub from release branch
  - provider: script
    script: bash deploy.sh
    on:
      branch: release