export const SWITCH_APPLICATION = 'SWITCH_APPLICATION';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const SET_SIDEBAR = 'SET_SIDEBAR';

export const LOAD_TOGGLES = 'LOAD_TOGGLES';
export const TOGGLES_LOADED = 'TOGGLES_LOADED';